### ISSUE TITLE
No LICENSE file in pip package. Error on install

### ISSUE THREAD

**Issue by eacmen** [lzakharov/csv2md#1]
Get the following error when trying to install via pip:

```
$ pip3 install csv2md
Looking in indexes: https://pypi.org/simple
Collecting csv2md
  Using cached https://files.pythonhosted.org/packages/cc/1b/8855dc07a5c5821040eceb7934e1a772dff24dbf396b4cff4467b4e28904/csv2md-1.0.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-94m5gafj/csv2md/setup.py", line 7, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-94m5gafj/csv2md/
```

**Comment by lzakharov** [comment]
Thank you for your comment! Now everything works.
